#!/bin/sh

set -e

if [ "x$1" = xremove ]; then
	update-alternatives \
		--remove default.plymouth /usr/share/plymouth/themes/yoyo-logo/yoyo-logo.plymouth

        update-alternatives \
		--remove text.plymouth /usr/share/plymouth/themes/yoyo-text/yoyo-text.plymouth
fi

#DEBHELPER#
